# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Juggle < Formula
  desc "Task management CLI for autonomous AI agent loops"
  homepage "https://github.com/ohare93/juggle"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohare93/juggle/releases/download/v0.3.0/juggle_0.3.0_darwin_amd64.tar.gz"
      sha256 "d38b38a2535080b1e91e87f358b514e2dd7556e07aec473113315e77eaa7fb7c"

      def install
        bin.install "juggle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohare93/juggle/releases/download/v0.3.0/juggle_0.3.0_darwin_arm64.tar.gz"
      sha256 "140513157ce2009ae63ffdf14e3410e9045105a8c8568d47ee602aa0eb693dba"

      def install
        bin.install "juggle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohare93/juggle/releases/download/v0.3.0/juggle_0.3.0_linux_amd64.tar.gz"
      sha256 "d4edb7b7a022433afda58b5fa4693dcaafd68e7d721d81734d70d849a2efc938"
      def install
        bin.install "juggle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohare93/juggle/releases/download/v0.3.0/juggle_0.3.0_linux_arm64.tar.gz"
      sha256 "69b3a792ad97fe17051a0f00823542511d4089641d4febfe0ffe3c4502805e63"
      def install
        bin.install "juggle"
      end
    end
  end

  test do
    system "#{bin}/juggle", "--version"
  end
end
