# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Juggle < Formula
  desc "Task management CLI for autonomous AI agent loops"
  homepage "https://github.com/ohare93/juggle"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohare93/juggle/releases/download/v0.2.2/juggle_0.2.2_darwin_amd64.tar.gz"
      sha256 "1ff424f1657d6ee392e9aef96caabc188c5f92b5473a1c47c5944db4d85de2a6"

      def install
        bin.install "juggle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohare93/juggle/releases/download/v0.2.2/juggle_0.2.2_darwin_arm64.tar.gz"
      sha256 "bffdc3f27e1109a8584fb9bd446c417cf5e349975f062520dd13e828f927c8cd"

      def install
        bin.install "juggle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohare93/juggle/releases/download/v0.2.2/juggle_0.2.2_linux_amd64.tar.gz"
      sha256 "7a6d96cd67953b5a9b774b6225cfed49ea9164cdc892ee1a081ea1e22d53848d"
      def install
        bin.install "juggle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohare93/juggle/releases/download/v0.2.2/juggle_0.2.2_linux_arm64.tar.gz"
      sha256 "4c3ecd4119211fdeb832e15a1a84f269f335493b5148d34bcb073de3feab5edb"
      def install
        bin.install "juggle"
      end
    end
  end

  test do
    system "#{bin}/juggle", "--version"
  end
end
